apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncshield.syncvalueFullname" . }}
  labels: {{ include "syncshield.labels" . | nindent 4 }}
    app.kubernetes.io/component: syncvalue
spec:
  type: {{ .Values.syncvalue.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "syncshield.name" . }}
    app.kubernetes.io/component: syncvalue
  ports:
    - name: grpc
      port: {{ .Values.syncvalue.service.grpcPort }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.syncvalue.service.metricsPort }}
      targetPort: metrics
